source "https://github.com/CocoaPods/Specs.git"

target 'TangramCategoryDemo' do
platform :ios, '7.0'

    pod 'Tangram' , :path=>'../'
    pod 'Reachability', '~>3.2'
    pod 'SDWebImage'
    pod 'Masonry'
	
end
